# render.yaml
# This file configures a standalone Cron Job service on Render.
# Its sole purpose is to generate "Spot the Difference" game levels and
# upload them to a cloud storage bucket.

services:
  # Service Definition for the AI Level Generator
  - type: cron
    name: spot-the-difference-generator
    runtime: python
    plan: free
    
    # Directory containing the service's code
    rootDir: ./ai_generator
    
    # Build command to install dependencies
    buildCommand: "pip install -r requirements.txt"
    
    # Command to execute on schedule
    startCommand: "python generate_level.py"
    
    # Schedule: Runs at minute 0 past every 6th hour. (e.g., 00:00, 06:00, 12:00, 18:00 UTC)
    schedule: "0 */6 * * *"
    
    # Environment variables for the service.
    # Set sensitive values in the Render dashboard.
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"

      # --- API Keys and Cloud Storage Credentials ---
      # You MUST set these values manually in the Render dashboard for security.
      - key: OPENAI_API_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: S3_ENDPOINT_URL
        sync: false # e.g., https://fra1.digitaloceanspaces.com (the URL for your bucket's region)
