# render.yaml
# This file configures a standalone Cron Job service on Render.
# Its sole purpose is to generate "Spot the Difference" game levels and
# upload them to a cloud storage bucket using images from the repository.

services:
  # Service Definition for the AI Level Generator
  - type: cron
    name: spot-the-difference-generator
    runtime: python
    plan: free
    
    # Directory containing the service's code
    rootDir: ./ai_generator
    
    # Build command to install dependencies
    buildCommand: "pip install -r requirements.txt"
    
    # Command to execute on schedule. It will randomly pick an image from the
    # images_for_ai directory and process it.
    startCommand: >
      IMAGE_FILE=$(find ../images_for_ai -type f | shuf -n 1) &&
      echo "Processing image: $IMAGE_FILE" &&
      python generate_level.py "$IMAGE_FILE"
    
    # Schedule: Runs every 10 minutes for testing. 
    # You can change this back to a less frequent schedule like "0 */6 * * *"
    schedule: "*/10 * * * *"
    
    # Environment variables for the service.
    # Set sensitive values in the Render dashboard.
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"

      # --- Cloud Storage Credentials ---
      # You MUST set these values manually in the Render dashboard for security.
      # The S3_ENDPOINT_URL is your Cloudflare R2 account ID URL.
      # e.g., https://<account_id>.r2.cloudflarestorage.com
      - key: S3_ENDPOINT_URL
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
