name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          # v3 might not require explicit api-level/build-tools inputs,
          # but an empty 'with:' ensures correct syntax for potential future options.
          # The action should add necessary tools to PATH.

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./android

      - name: Build Release APK
        run: ./gradlew assembleRelease
        working-directory: ./android

      - name: Sign APK
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > release-key.jks
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore release-key.jks -storepass ${{ secrets.SIGNING_KEYSTORE_PASSWORD }} ./app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.SIGNING_KEY_ALIAS }}
          zipalign -v 4 ./app/build/outputs/apk/release/app-release-unsigned.apk ./app/build/outputs/apk/release/app-release-signed.apk
        working-directory: ./android

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: ./android/app/build/outputs/apk/release/app-release-signed.apk

