name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Decode Keystore
      run: echo "${{ secrets.SIGN_KEY }}" | base64 --decode > android/release-key.jks

    - name: DEBUG - Verify Gradle Wrapper
      working-directory: ./android
      run: |
        echo "--- Verifying gradlew script ---"
        ls -l gradlew
        cat gradlew | head -n 5
        echo "--- Verifying wrapper jar existence and content ---"
        ls -l gradle/wrapper/gradle-wrapper.jar
        jar -tvf gradle/wrapper/gradle-wrapper.jar | grep GradleWrapperMain || echo "GradleWrapperMain.class not found in jar!"
        echo "--- End of verification ---"

    - name: Build with Gradle (Bypassing gradlew script)
      working-directory: ./android
      run: |
        java \
          -Dorg.gradle.appname=gradlew \
          -cp gradle/wrapper/gradle-wrapper.jar \
          org.gradle.wrapper.GradleWrapperMain :app:assembleRelease --stacktrace
      env:
        SIGNING_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
