name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate a new, valid Gradle Wrapper
      uses: gradle/gradle-build-action@v2
      with:
        generate-gradle-wrapper: true
        gradle-version: 8.7
        build-root-directory: android

    - name: Decode Keystore
      run: echo "${{ secrets.SIGN_KEY }}" | base64 --decode > android/release-key.jks

    - name: Build with the newly generated Gradle Wrapper
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :app:assembleRelease --stacktrace
        build-root-directory: android
      env:
        SIGNING_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
