name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Decode Keystore
      run: echo "${{ secrets.SIGN_KEY }}" | base64 --decode > android/release-key.jks

    - name: Diagnose and Download Gradle Wrapper
      run: |
        mkdir -p android/gradle/wrapper
        echo "--- Attempting to download gradle-wrapper.jar with verbose output ---"
        curl -v -L -o android/gradle/wrapper/gradle-wrapper.jar https://repo1.maven.org/maven2/org/gradle/gradle-wrapper/8.7/gradle-wrapper-8.7.jar
        echo "--- Download command finished. Verifying file content. ---"
        cat android/gradle/wrapper/gradle-wrapper.jar || echo "File is empty or could not be read."
        echo "--- Verification finished. ---"

    - name: Build with Gradle (Direct Java Call)
      working-directory: ./android
      run: |
        java \
          -Dorg.gradle.appname=gradlew \
          -cp gradle/wrapper/gradle-wrapper.jar \
          org.gradle.wrapper.GradleWrapperMain :app:assembleRelease --stacktrace
      env:
        SIGNING_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
