name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Decode Keystore
      run: echo "${{ secrets.SIGN_KEY }}" | base64 --decode > android/release-key.jks
      
    - name: Make gradlew executable
      run: chmod +x android/gradlew

    - name: Build with Gradle using the official action
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleRelease --stacktrace
        build-root-directory: android
      env:
        SIGNING_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
